<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Vanilla JS</title>
</head>

<body>

</body>

<!-- When this script is executed by the browser, it will get its own Global Execution content (GEC), then each function call will get its own Function Execution context (FEC). GEC will always be at the bottom of the callstack (LIFO). -->
<script>
  function varAndLetScope() {
    if (true) {
      var x = 5; // x is defined within the entire function because var is function-scoped
      let y = 6; // y is only defined within this if block because let is block-scoped
    }

    console.log('var: ', x); // This will output '5'.
    console.log('let: ', y); // This will throw a ReferenceError: y is not defined.
  }

  varAndLetScope();
</script>

<!-- by value or by reference: -->
<script>
  let a = { foo: "bar" }
  let b = a
  // b => { foo: "bar" }

  b.baz = "qux"
  // a, b => { foo: "bar", baz: "qux" }

  a = {}
  // a => {}
  // b => { foo: "bar", baz: "qux" }
  // assigning a new object breaks the reference change
</script>

<script>
  //
  console.log(1);

  // macrotask 
  setTimeout(() => console.log(2));

  // microtask
  Promise.resolve().then(() => console.log(3));

  // microtask => macrotask
  Promise.resolve().then(() => setTimeout(() => console.log(4)));

  // microtask
  Promise.resolve().then(() => console.log(5));

  // macrotask
  setTimeout(() => console.log(6));

  //
  console.log(7);
</script>



<script>
  // A single promise can have multiple then handlers attached to it
  let p = Promise.resolve('p value');

  // each of these handlers will be added to the microtask queue without waiting for one another and will recieve the same value from resolve(). They do NOT depend on each other.
  p.then(value => {
    console.log('first handler:', value); // => "first handler: p value
  });

  p.then(value => {
    console.log('second handler:', value); // => "second handler: p value"
  });


  // ..or a single promise can have a single then handler
  let p2 = Promise.resolve('p2 value');

  // p2 has a single then handler. The handler returns a NEW promise which has its own then handler. The next handler in the chain will only be be executed and added to the microtask queue once the previous one has resolved. Each subsequent handler returns a NEW promise and is given a value from the previous handlers resolve function. Unlike the first example, they all depend on each other. Ultimately the return value of this chain will be the Promise object of the last promise in the chain
  p2.then(value => {
    console.log('first handler:', value); // => "first handler: p2 value

    // Even if you dont explicitly return a Promise, then will return a new promise that immediately resolves with the return value, or rejects if an error is thrown
    return 'Value from first handler';
  }).then(value => {
    console.log('second handler:', value); // => "second handler: value from first handler"
  });

  // catch handlers also return a promise allowing them to be chained:
  Promise.reject("Error")
    .then(result => {
      console.log("This won't be called");
      return result;
    })
    .catch(error => {
      console.log("Caught:", error); // Logs: "Caught: Error"
      return "Recovered";  // Resolve the promise with "Recovered"
    })
    // this handler belongs to the new promise returned by catch:
    .then(result => {
      console.log("After recovery:", result); // Logs: "After recovery: Recovered"
    })
    .catch(error => {
      console.log("This won't be called either");
    });

  // since fetch supports promises, you can imagine it internally returns a Promise constuctor that triggers some raw HTTP API and passes it a callback that calls resolve() or reject() depending on the result of the HTTP request.
  // If it didn't support promises, we would directly pass it a callback to be executed instead, like the old days.
  let promise = fetch('https://jsonplaceholder.typicode.com/posts/1');

  // .then ALWAYS returns a NEW promise
  promise.then(res => {
    if (!res.ok) {
      throw new Error(`HTTP error! status: ${res.status}`);
    }
    // returns a new promise:
    return res.json();
  })
    // When your callback explicitly returns a promise, the new promise created and returned by .then will be synced up to your promise and will resolve with its value. If your promise has its own chain of promises, it will resolve with the value of the last promise in the chain. No matter how nested it gets, .then will always returns a new promise that resolves with the last value in your chain.
    .then(data => {
      let promise2 = new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve("Promise2 resolved!");
        }, 1000);
      });

      return promise2
        .then(data => {
          console.log(value2); // logs "Promise2 resolved!"
          return "Value from Promise2's .then()";
        });
    })
    .then(data => {
      console.log(data); // logs "Value from Promise2's .then()"

      setTimeout(() => {
        console.log("Timeout completed!");
      }, 2000);
    })
    .then(data => {
      console.log(data); // logs undefined
    })
    .catch(error => {
      console.log(`Fetch Error: ${error}`);
    });

  // just like with .then, the return value of an async function will be a new promise that either resolves with the return value or rejects if an error is thrown
  async function asyncFunction() {
    console.log("Start");
    // NOTE: the body of the promises will be executed immediately (scheduling the setTimeout)
    await new Promise(resolve => setTimeout(resolve, 1000));
    await new Promise(resolve => setTimeout(resolve, 1000));
    console.log("End");
    // return Promise.resolve(undefined) => in this case you can think of this being the return value
  }

  // since an async function also returns a promise, you can chain handlers onto it (these will run once the entire body of the async function completes and it finally returns.
  asyncFunction()
    .then(() => {
      console.log('asyncFunction then')
    })
    .catch((err) => {
      console.log(err)
    })

  // Async Function Flow:
  // - async func body is executed synchronously until it encounters an await

  // - it executes the awaited promise and waits for it to resolve.

  // - while waiting, the function is released from the callstack allowing the rest of the script outside the function to continue executing (and the event loop to process other events). The engine remembers the exact execution context of the async function and which line to resume from when the awaited promise resolves.

  // the cycle continues for every await that is encountered inside of it

  // (Dont worry about the exact details of this works. how async / await is actually handled is an implementationd detail of the engine)
</script>

</html>